version: "3.8"

services:
  doctor-booking-api:
    build:
      context: ..
      dockerfile: ./devops/Dockerfile
    container_name: doctor-booking-api
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    volumes:
      - ../:/app
      - /app/node_modules
    env_file:
      - ../.env
    command: npm run start:dev

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
