version: "3.8"

services:
  doctor-booking-api:
    build:
      context: ..
      dockerfile: ./devops/Dockerfile
    container_name: doctor-booking-api
    ports:
      - "3001:3001"
    depends_on:
      - mongo
      - redis
    volumes:
      - ../:/app
      - /app/node_modules
    env_file:
      - ../.env
    command: npm run start:dev

  doctor-booking-api-consumer:
    build:
      context: ..
      dockerfile: ./devops/Dockerfile
    container_name: doctor-booking-api-consumer
    ports:
      - "3002:3002"
    depends_on:
      - mongo
      - redis
    volumes:
      - ../:/app
      - /app/node_modules
    env_file:
      - ../.env
    environment:
      - IS_CONSUMER_SERVER=true
    command: npm run start:dev

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  mongo_data:
